2018年01月09日 (火) 著者 ： nobuh  
https://www.infiniteloop.co.jp/blog/2018/01/learning-keras-04/

In [9]:
from sklearn import datasets

iris=datasets.load_iris()
print(iris.keys())

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [11]:
print(iris["data"].shape)
print(iris["target"].shape)
print(iris["target_names"])
print(iris["feature_names"])

(150, 4)
(150,)
['setosa' 'versicolor' 'virginica']
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [12]:
X=iris.data
T=iris.target

In [19]:
X[0]

array([5.1, 3.5, 1.4, 0.2])

In [21]:
T[0]

0

one-hotに変換します。

In [22]:
from keras.utils import np_utils

T=np_utils.to_categorical(T)

In [23]:
T[0]

array([1., 0., 0.], dtype=float32)

In [24]:
from sklearn.model_selection import train_test_split
import numpy as np

np.random.seed(0) # 乱数初期化を固定値に

In [28]:
train_x,test_x,train_t,test_t=train_test_split(X,T,test_size=0.2)
print(len(train_x),len(test_x),len(train_t),len(test_t))

120 30 120 30


# 単純なパーセプトロン

In [29]:
from keras.models import Sequential
from keras.layers import Dense,Activation
from keras.optimizers import SGD

model=Sequential()
model.add(Dense(input_dim=4,units=3)) # 入力が4種の特徴、3つに分類
model.add(Activation("softmax"))
model.compile(loss="categorical_crossentropy",optimizer=SGD(lr=0.1))
model.fit(train_x,train_t,epochs=50,batch_size=10) # エポック数50、ミニバッチ10

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use tf.cast instead.
Epoch 1/50
120/120 [==============================] - 1s 5ms/step - loss: 1.4624
Epoch 2/50
120/120 [==============================] - 0s 233us/step - loss: 0.9812
Epoch 3/50
120/120 [==============================] - 0s 331us/step - loss: 0.8303
Epoch 4/50
120/120 [==============================] - 0s 647us/step - loss: 0.7189
Epoch 5/50
120/120 [==============================] - 0s 305us/step - loss: 0.6484
Epoch 6/50
120/120 [==============================] - 0s 320us/step - loss: 0.4588
Epoch 7/50
120/120 [==============================] - 0s 282us/step - loss: 0.8078
Epoch 8/50
120/120 [==============================] - 0s 289us/step - loss: 0.4871
Epoch 9/50
120/120 [==============================] - 0s 340us/step - loss: 0.8521
Epoch 10/50
120/120 [==============================] - 0s 257us/step - loss: 0.4397
Epoch 11/50
120/120 [==============================

In [30]:
Y=model.predict_classes(test_x,batch_size=10) # ミニバッチは訓練時と同じ10

In [31]:
Y

array([1, 2, 1, 2, 2, 2, 2, 0, 0, 1, 2, 2, 1, 1, 2, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0])

In [32]:
import numpy as np

_,T_index=np.where(test_t>0)
print(T_index)

[1 2 1 2 2 2 2 0 0 1 2 2 1 1 2 1 1 1 0 2 0 0 0 1 0 0 1 0 1 0]


In [34]:
Y==T_index

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])