入門 Keras (1) Windows に Tensorflow と Keras をセットアップ  
https://www.infiniteloop.co.jp/blog/2017/11/learning-keras-01/  
2017年11月20日 (月) 著者 ： nobuh  

In [2]:
import numpy as np

a=np.arange(1,10).reshape(3,3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
import tensorflow as tf

hello=tf.constant("Hello Tensorflow!")
sess=tf.Session()
print(sess.run(hello))

b'Hello Tensorflow!'


# MNIST

In [4]:
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense,Dropout,Flatten,Conv2D,MaxPooling2D
from keras import backend as K

In [5]:
batch_size=128
num_classes=10
epochs=2

# input image dimensions
img_rows,img_cols=28,28

# the data, shuffled and split between train and test sets
(x_train,y_train),(x_test,y_test)=mnist.load_data()

11493376/11490434 [==============================] - 4s 0us/step


In [16]:
print(x_train.shape)
print(x_train[0,:,:]) # 1枚目の画像

(60000, 28, 28)


array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [19]:
print(y_train.shape)
print(y_train[:10]) # 10枚目までのラベル

(60000,)
[5 0 4 1 9 2 1 3 1 4]


In [20]:
print(x_test.shape)
print(y_test.shape)

(10000, 28, 28)
(10000,)


In [21]:
if K.image_data_format()=="channels_first":
    x_train=x_train.reshape(x_train.shape[0],1,img_rows,img_cols)
    x_test=x_test.reshape(x_test.shape[0],1,img_rows,img_cols)
    input_shape=(1,img_rows,img_cols)
else:
    x_train=x_train.reshape(x_train.shape[0],img_rows,img_cols,1)
    x_test=x_test.reshape(x_test.shape[0],img_rows,img_cols,1)
    input_shape=(img_rows,img_cols,1)
    
x_train=x_train.astype("float32")
x_test=x_test.astype("float32")
x_train/=255
x_test/=255

print("x_train shape:",x_train.shape)
print(x_train.shape[0],"train samples")
print(x_test.shape[0],"test samples")

# convert class vectors to binary class matrices
y_train=keras.utils.to_categorical(y_train,num_classes)
y_test=keras.utils.to_categorical(y_test,num_classes)

x_train shape: (60000, 28, 28, 1)
60000 train samples
10000 test samples


In [26]:
model=Sequential()
model.add(Conv2D(32,kernel_size=(3,3),activation="relu",input_shape=input_shape))
model.add(Conv2D(64,(3,3),activation="relu"))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128,activation="relu"))
model.add(Dropout(0.5))
model.add(Dense(num_classes,activation="softmax"))

model.compile(
    loss=keras.losses.categorical_crossentropy,
    optimizer=keras.optimizers.Adadelta(),
    metrics=["accuracy"]
)

In [27]:
model.fit(
    x_train,y_train,
    batch_size=batch_size,
    epochs=epochs,
    verbose=1,
    validation_data=(x_test,y_test)
)

score=model.evaluate(x_test,y_test,verbose=0)
print("Test loss:",score[0])
print("Test accuracy:",score[1])

Instructions for updating:
Use tf.cast instead.
Train on 60000 samples, validate on 10000 samples
Epoch 1/2
60000/60000 [==============================] - 111s 2ms/step - loss: 0.2468 - acc: 0.9257 - val_loss: 0.0578 - val_acc: 0.9808
Epoch 2/2
60000/60000 [==============================] - 106s 2ms/step - loss: 0.0931 - acc: 0.9724 - val_loss: 0.0464 - val_acc: 0.9840
Test loss: 0.04639517976447241
Test accuracy: 0.984
